name: Build Incus Image
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build-Incus-Image:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install -y debootstrap rsync gpg squashfs-tools git
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.5' 
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/checkout@master
        with:
          repository: lxc/distrobuilder
      - run: cd distrobuilder
      - run: go env
      - run: make
      - run: cd ${{ github.workspace }}
      - name: Adding distrobuilder to path  
        run: echo "/home/runner/go/bin" >> $GITHUB_PATH
      - name: Build Incus Image
        run: |
          sudo /home/runner/go/bin/distrobuilder build-incus ubuntunocloud.yaml ubuntunocloud
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
